Arulprasath36/WhatsUp_Development

WhatsUP.txt
Kindly review and merge this branch. this includes audio and video calls feature.
=> Added audio video calls feature

WhatsUP.txt
Dear Arulprasath,
You are doing an amazing job. I have added one more feature to your product. Kindly review and merge to the original code.
Thanks,
LAO
=> added status feature

WhatsUP.txt
Reverts Arulprasath36/WhatsUp_Development#3
=> Revert "adding attachments of PDF and docs"

WhatsUP.txt
Dear Arulprasath,
You are doing a great service. I have added a new feature called status. Using this the user can run trains. Kindly review and merge this to your code.
=> Added a status feature

WhatsUP.txt
Dear Arul,
I have included a new group feature to add upto 100 users. Kindly review and merge the code.
=> including group feature

WhatsUP.txt
Hi Arul,
I have added group features. Using this we can add around 200 users. Kindly review and merge this code.
=> Added group features

Adding Demo 1, WhatsUP.txt
Dear ArulPrasath
You are doing great job
=> Added feature

Adding Demo 1
Hi Arul,
Your teaching is good. Kindly add my changes.
=> Added feature 6

WhatsUP.txt
Hai arul sir
Your doing well. I have added some new feature in group video chat and hiding status kindly review and merge this code sir
=> Added a group video call and status hiding

Adding Demo 1
Hi Arul,
Practicing this to do home work given by you in Video 4 of Github tutorials
=> Added one new feature

WhatsUP.txt
Dear Arul,
Its a fine job of sharing knowledge. Kindly review and merge this code if needed.
=> Added new features

WhatsUP.txt
Please add the code..thanks for ur support Arul
=> Connecting people

WhatsUP.txt
Hi Bro,
Your teaching skill is totally different from others and really you are very good at that. plz approve my pull request
=> I have been added Dark mode feature in watsapp application

README.md
Dear arulprasath,]
you are very great sir kindly review the added diz code
=> added a status featuress

WhatsUP.txt
Added Last seen disable feature has been added successfully. Using this, the user can disable their last seen status.
=> Added Last seen disable feature

WhatsUP.txt
=> added a video game

WhatsUP.txt
Dear Sir,
I want to block my manager in my status because of privacy issues related to work. Kindly add this change to your code.
Regards,
Bhavishya
=> Block users in status

WhatsUP.txt
Dear Arulprasath sir, you are doing amazing job. i have added some extra features by using your file .Kindly review and merge this to your code
=> Thanking arul sir for his amazing videos

WhatsUP.txt
Dear sir,
Your videos are awesome, I have added  payments options in your existing code, Kindly review and merge this code,
Thank you.
=> Added payment features

WhatsUP.txt
Dear Sir,
Thanks for your support. Kindly review my code if found useful, accept it
=> Sharing photo & video with original resolution
